# This is a basic workflow to help you get started with Actions
# https://crontab.guru/

name: daily_deleter

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '0 23 * * 1-5'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job_1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # required to access files on github repo (.py files etc)
    - uses: actions/checkout@v2
    # Runs a set of commands using the runners shell
    - name: runner
      env: # Or as an environment variable
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        pip install wheel
        pip install requests
        pip install bs4
        pip install python-decouple
        echo "Do something here"
